version: '3'

services:
  web-proxy:
    image: jwilder/nginx-proxy
    container_name: web-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  web-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: web-proxy-letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:rw
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  sparkcc-wiki-db:
    image: mongo
    container_name: sparkcc-wiki-db
    restart: unless-stopped
    expose:
      - '27017'
    command: '--smallfiles --bind_ip sparkcc-wiki-db'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - sparkcc-wiki-db-data:/data/db
  sparkcc-wiki:
    image: 'requarks/wiki:latest'
    container_name: sparkcc-wiki
    restart: unless-stopped
    links:
      - sparkcc-wiki-db
    depends_on:
      - sparkcc-wiki-db
    ports:
      - '8001:3000'
    environment:
      - WIKI_ADMIN_EMAIL=admin@sparkcc.org
      - VIRTUAL_HOST=wiki.sparkcc.org
      - LETSENCRYPT_HOST=wiki.sparkcc.org
      - LETSENCRYPT_EMAIL=admin@sparkcc.org
    volumes:
      - sparkcc-wiki-data:/data
      - sparkcc-wiki-repo:/repo
      - /data/sparkcc-wiki/config/config.yml:/var/wiki/config.yml
  sparkcc-hq:
    image: php:7.2-apache
    container_name: sparkcc-hq
    restart: unless-stopped
    links:
      - sparkcc-hq-db
    depends_on:
      - sparkcc-hq-db
    ports:
      - '8002:80'
    environment:
      - WIKI_ADMIN_EMAIL=admin@sparkcc.org
      - VIRTUAL_HOST=wiki.sparkcc.org
      - LETSENCRYPT_HOST=wiki.sparkcc.org
      - LETSENCRYPT_EMAIL=admin@sparkcc.org
  sparkcc-hq-db:
    image: mariadb
    container_name: sparkcc-hq-db
    restart: unless-stopped
    volumes:
      - sparkcc-hq-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${HQ_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${HQ_MYSQL_SPARKCC_PASSWORD}
      - MYSQL_DATABASE=sparkcc
      - MYSQL_USER=sparkcc

volumes:
  proxy-certs:
    driver: local-persist
    driver_opts:
      mountpoint: /data/www-proxy/certs
  proxy-vhosts:
    driver: local-persist
    driver_opts:
      mountpoint: /data/www-proxy/vhosts
  proxy-html:
    driver: local-persist
    driver_opts:
      mountpoint: /data/www-proxy/html
  sparkcc-wiki-data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/sparkcc-wiki/data
  sparkcc-wiki-repo:
    driver: local-persist
    driver_opts:
      mountpoint: /data/sparkcc-wiki/repo
  sparkcc-wiki-db-data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/sparkcc-wiki-db/data
  sparkcc-hq-db-data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/sparkcc-hq-db/data
