version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: web-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  sparkcc-wiki:
    image: nyarla/realms-wiki-alpine
    container_name: sparkcc-wiki 
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      REALMS_WIKI_CONFIG: >- 
        {
        "SITE_TITLE": "SparkCC Wiki",
        "DB_URI": "sqlite:////opt/data/wiki.db",
        "WIKI_PATH": "/opt/data/wiki"
        }
      VIRTUAL_HOST: "wiki.sparkcc.org"
    volumes:
      - wiki_data:/opt/data

volumes:
  wiki_data:
    driver: local-persist
    driver_opts:
      mountpoint: /var/data/wiki/
