version: '3.8'

services:
  web-proxy:
    image: jwilder/nginx-proxy
    container_name: web-proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-vhosts:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - proxy-dhparam:/etc/nginx/dhparam
      - proxy-conf:/etc/nginx/conf.d
  web-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: web-proxy-acme
    restart: unless-stopped
    volumes_from:
      - web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:rw
      - proxy-acme:/etc/acme.sh
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --interval 30 --label-enable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  membermatters:
    image: membermatters/membermatters:v3.3.0
    container_name: membermatters
    restart: unless-stopped
    ports:
      - '8004:8000'
    volumes:
      - 'membermatters:/usr/src/data'
    environment:
      - PORTAL_DOMAIN=https://members.sparkcc.org
      - PORTAL_ENV=Production
      - VIRTUAL_HOST=members.sparkcc.org
      - LETSENCRYPT_HOST=members.sparkcc.org
      - LETSENCRYPT_EMAIL=admin@sparkcc.org
  sparkcc-www:
    image: microweber/microweber:v1.2.19
    container_name: sparkcc-www
    restart: unless-stopped
    ports:
      - "8005:80"
    environment:
      - VIRTUAL_HOST=www.sparkcc.org,sparkcc.org
      - LETSENCRYPT_HOST=www.sparkcc.org,sparkcc.org
      - LETSENCRYPT_EMAIL=admin@sparkcc.org
    volumes:
      - sparkcc-www:/var/www/html
  sparkcc-wiki-db:
    image: postgres:11-alpine
    container_name: sparkcc-wiki-db
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_PASSWORD=${WIKI_DB_PASSWORD}
      - POSTGRES_USER=wiki
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - sparkcc-wiki-db:/var/lib/postgresql/data
  sparkcc-wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: sparkcc-wiki
    depends_on:
      - sparkcc-wiki-db
    restart: unless-stopped
    ports:
      - "8006:3000"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=sparkcc-wiki-db
      - DB_PORT=5432
      - DB_USER=wiki
      - DB_PASS=${WIKI_DB_PASSWORD}
      - DB_NAME=wiki
      - WIKI_ADMIN_EMAIL=admin@sparkcc.org
      - VIRTUAL_HOST=wiki.sparkcc.org
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=wiki.sparkcc.org
      - LETSENCRYPT_EMAIL=admin@sparkcc.org

  volumes-backup:
    image: jareware/docker-volume-backup:2.6.0
    restart: always
    environment:
      BACKUP_CRON_EXPRESSION: "30 02 * * *"
      BACKUP_FILENAME: "sparkcc-cloud_volumes-%Y-%m-%dT%H-%M-%S.tar.gz"
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: sparkcc-prod-backups/sparkcc-cloud_volumes
    volumes:
      - membermatters:/backup/membermatters:ro
      - sparkcc-www:/backup/sparkcc-www:ro
      - sparkcc-wiki-db:/backup/sparkcc-wiki-db:ro

volumes:
  proxy-certs:
  proxy-vhosts:
  proxy-html:
  proxy-dhparam:
  proxy-conf:
  proxy-acme:
  membermatters:
  sparkcc-www:
  sparkcc-wiki-db:
